// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYod-Gg3IdcnXXMxR6p8iYqVIT22BRxW8',
    appId: '1:592823284758:web:4c57bdb1e4cdaa71d8f137',
    messagingSenderId: '592823284758',
    projectId: 'mislabs123890',
    authDomain: 'mislabs123890.firebaseapp.com',
    storageBucket: 'mislabs123890.appspot.com',
    measurementId: 'G-6ZFVYWG5WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC5hkr4Mvs6c7_LyhlS-w9dKj35CMDI6E',
    appId: '1:592823284758:android:0477b5cf483f9349d8f137',
    messagingSenderId: '592823284758',
    projectId: 'mislabs123890',
    storageBucket: 'mislabs123890.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkIvElHKcgcs7_db8gLAlGcXFtHZdraQ4',
    appId: '1:592823284758:ios:cc15d9153ea23e17d8f137',
    messagingSenderId: '592823284758',
    projectId: 'mislabs123890',
    storageBucket: 'mislabs123890.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkIvElHKcgcs7_db8gLAlGcXFtHZdraQ4',
    appId: '1:592823284758:ios:9d3d9aa1364e726fd8f137',
    messagingSenderId: '592823284758',
    projectId: 'mislabs123890',
    storageBucket: 'mislabs123890.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
